language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5"
  - "6"
os:
  - linux
  - osx
before_script:
  - npm install -g webpack
  - npm install -g gulp
  - npm install -g gulp-cli
  - npm install -g mocha